services:
  hetzner-traffic-guard:
    build: .
    container_name: hetzner-traffic-guard
    restart: unless-stopped
    ports:
      - "1227:1227"
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./state:/app/state
      - ./:/opt/hzc
      - /var/run/docker.sock:/var/run/docker.sock
